version: "3.6"
services:
  nginxphp:
    build: 
      context: ../
      dockerfile: ./docker/nginxphp/DevDockerfile
    container_name: nginxphp
    image: devnginxphp
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ../source/
        target: /var/www/
  composer:
    image: composer:1.9
    working_dir: "/var/www/"
    container_name: composer
    command: 'composer update && composer dump-autoload -o'
    depends_on:
      - nginxphp
    volumes:
      - type: bind
        source: ../source/
        target: /var/www/