version: "3.6"
services:
  nginxphp:
    build: 
      context: ../
      dockerfile: ./docker/nginxphp/DevDockerfile
    container_name: nginxphp
    image: devnginxphp
    depends_on:
      - composer
      - mongodb
    ports:
      - 80:80
    networks:
      - db_network
    volumes:
      - type: bind
        source: ../source/
        target: /var/www/
  composer:
    image: composer:1.9
    working_dir: "/var/www/"
    container_name: composer
    command: '/bin/sh /scripts/mongo_install_composer.sh && composer update && composer dump-autoload -o'
    volumes:
      - type: bind
        source: ../source/
        target: /var/www/
      - type: bind
        source: ../docker/composer/
        target: /scripts/
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    expose:
      - 27017
    networks:
      - db_network
networks:
  db_network: